version: '3'
services:
  redis:
    image: redis:6.2-alpine
    restart: always
    command: redis-server --save 60 1
    volumes:
      - ./node-server/cache/redis:/data
  node-server:
    build: ./node-server
    ports:
      - "9090:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./node-server/cache:/weavedb/cache
    depends_on:
      - redis
  envoy:
    build: ./envoy
    ports:
      - "8080:8080"    